### ISSUE TITLE
ImmediatelyFast supports VulkanMod

### ISSUE THREAD

**Issue by RaptaG** [intergrav/vulkadrenaline#1]
You should include it again

**Comment by intergrav** [comment]
ImmediatelyFast's `fabric.mod.json` says that it breaks VulkanMod, and prevents launching the game:
```json
"breaks": {
  "optifabric": "*",
  "vulkanmod": "*"
},
```
I'll try making a dependency override, maybe it'll work then

**Comment by intergrav** [comment]
I'll close this for now but if it is supported in the future, feel free to reopen it
